r"""Write the two TikZ mechanism figures of the manuscript into theory.tex.

Figure 2 (Section 2.3) draws why a fixed indicator loses information and
what that costs a replacement decision; Figure 3 (Section 3) draws why the
informative direction turns, which component of its motion changes the
misalignment, and why the arc bounds the loss. theory.tex holds the output
between the markers %<mechfig:loss> and %<mechfig:arc>; this script
regenerates that text, so the geometry below is the only place to edit it.

Every drawn quantity that stands for a statement of the paper is computed,
not placed by eye, and asserted:
  * the two conditional densities in Fig. 2(c) have the same probability
    alpha below the lead time, and their centres sit zeta_alpha standard
    deviations above it;
  * the projected signal in Fig. 2(b) is sqrt(gamma) cos(psi);
  * in Fig. 3(a) the two growth steps have equal and unequal logarithmic
    rates, and the drawn turn is the true angle between the vectors;
  * in Fig. 3(b) the view is the orthographic projection centred on v, in
    which the sets of constant psi are exactly circles of radius sin(psi);
  * in Fig. 3(c) the midpoint is the midpoint by arc length, the cap has
    angular radius Phi/2 about it, every point of the path lies inside, and
    every drawn point is on the visible hemisphere.
Label positions are computed from the same geometry; the collision gate
(text over stroke, text over text, width) runs on the compiled pages.
Usage: python make_mechfigs.py   (rewrites the two blocks inside theory.tex)
"""
import io
import math
import os
import re

import numpy as np
from scipy.stats import norm

HERE = os.path.dirname(os.path.abspath(__file__))
TEX = os.path.join(HERE, "theory.tex")


def f(x):
    s = f"{x:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def pt(p):
    return f"({f(p[0])},{f(p[1])})"


def coords(P):
    return " ".join(pt(p) for p in P)


def polar(deg, r):
    return r * np.array([math.cos(math.radians(deg)), math.sin(math.radians(deg))])


TOP = 4.05                    # the baseline row of the panel titles

# =========================================================== Figure 2 =====
# ---- (a) time-shift population: common path x(s), units on it -----------
def xpath(s):
    return np.array([3.5 * s, 3.0 * (0.2 * s + 0.8 * s ** 3)])


def xtan(s):
    t = np.array([3.5, 3.0 * (0.2 + 2.4 * s ** 2)])
    return t / np.linalg.norm(t)


S_UNITS = (0.25, 0.42, 0.62, 0.86)
S0 = 0.62                     # the unit whose tangent is drawn
P0, T0 = xpath(S0), xtan(S0)
TIP_A = P0 + 0.8 * T0
path_a = [xpath(s) for s in np.linspace(0, 1, 61)]

# ---- (b) whitened record: sqrt(gamma) = 2 noise sd, psi = 50 deg --------
UNIT = 0.62                   # cm per noise standard deviation
SQG = 2.0                     # sqrt(gamma)
TH_D, PSI = 62.0, 50.0        # direction of d-hat, misalignment
TH_V = TH_D - PSI
ud, uv = polar(TH_D, 1.0), polar(TH_V, 1.0)
nd = np.array([-ud[1], ud[0]])
E_top = SQG * UNIT * ud
proj = E_top @ uv
assert abs(proj - SQG * UNIT * math.cos(math.radians(PSI))) < 1e-12
F_top = proj * uv
B_SHIFT = np.array([6.65, 1.75])

# ---- (c) conditional density of R when the policy replaces ---------------
ALPHA = 0.05
ZETA = norm.ppf(1 - ALPHA)
S_R, INFL = 0.33, 1.6         # cm; e^l drawn at 1.6 for legibility
T_LEAD, BASE, AMP = 1.0, 0.95, 0.55
curves = {}
for key, sd in (("rec", S_R), ("ind", INFL * S_R)):
    m = T_LEAD + ZETA * sd
    xs = np.linspace(max(0.05, m - 3.3 * sd), m + 3.3 * sd, 90)
    ys = BASE + AMP / sd * np.exp(-0.5 * ((xs - m) / sd) ** 2)
    xt = np.linspace(xs[0], T_LEAD, 30)
    yt = BASE + AMP / sd * np.exp(-0.5 * ((xt - m) / sd) ** 2)
    # the tail below the lead time has probability alpha, for both
    assert abs(norm.cdf((T_LEAD - m) / sd) - ALPHA) < 1e-12
    curves[key] = dict(m=m, sd=sd, xs=xs, ys=ys, xt=xt, yt=yt,
                       peak=BASE + AMP / sd)
assert curves["ind"]["m"] > curves["rec"]["m"]
rec, ind = curves["rec"], curves["ind"]


def dens(c, x):
    return BASE + AMP / c["sd"] * math.exp(-0.5 * ((x - c["m"]) / c["sd"]) ** 2)


# where each curve is crossed at a label's height, so the label clears it
LAB_REC = np.array([rec["m"] + 0.33, BASE + 0.85 * (rec["peak"] - BASE)])
LAB_IND = np.array([ind["m"] + 0.72, BASE + 0.55 * (ind["peak"] - BASE)])
assert dens(rec, LAB_REC[0]) < LAB_REC[1] - 0.05
assert dens(ind, LAB_IND[0]) < LAB_IND[1] - 0.05
TAIL = [(x, y) for x, y in zip(ind["xt"], ind["yt"])]


def tail_fill(c, colour):
    return (rf"\fill[{colour}] plot coordinates {{{coords(zip(c['xt'], c['yt']))}}}"
            rf" -- ({f(T_LEAD)},{f(BASE)}) -- ({f(c['xt'][0])},{f(BASE)}) -- cycle;")


fig_loss = rf"""%<mechfig:loss> generated by make_mechfigs.py -- edit there, not here
\begin{{figure*}}[tb]
\centering
\begin{{tikzpicture}}[font=\scriptsize, >={{Latex[length=1.5mm]}},
  ttl/.style={{font=\footnotesize, anchor=north}}]
% (a) time-shift population in damage space
\node[ttl] at (1.95,{f(TOP)}) {{(a) time-shift population}};
\draw[->] (0,0) -- (3.9,0) node[below left=1pt and -2pt] {{$x_1$}};
\draw[->] (0,0) -- (0,3.4) node[below left=-2pt and 1pt] {{$x_2$}};
\draw[thick] plot coordinates {{{coords(path_a)}}};
""" + "".join(rf"""\fill {pt(xpath(s))} circle (1.4pt);
""" for s in S_UNITS) + rf"""\draw[->, very thick, hired] {pt(P0)} -- {pt(TIP_A)};
\node[anchor=north west] at {pt(TIP_A + np.array([0.05, -0.08]))} {{$\dot x=-\partial x/\partial R$}};
\node[anchor=north west, align=left] at (0.1,3.3) {{units on one\\degradation path}};
% (b) the record seen through v
\begin{{scope}}[shift={{{pt(B_SHIFT)}}}]
\node[ttl] at (0,{f(TOP - B_SHIFT[1])}) {{(b) projection onto $\mathbf v$}};
\draw[gray!70] {pt(-1.6 * ud)} -- {pt(1.6 * ud)} node[above right=-2pt and -1pt] {{$\dhat$}};
\draw[hiblue] {pt(-1.7 * uv)} -- {pt(1.7 * uv)} node[right] {{$\mathbf v$}};
\draw[densely dashed, gray] (0,0) circle ({f(UNIT)});
\draw[line width=1.6pt] {pt(-E_top)} -- {pt(E_top)};
\draw[dashed, gray] {pt(E_top)} -- {pt(F_top)};
\draw[dashed, gray] {pt(-E_top)} -- {pt(-F_top)};
\draw[line width=1.6pt, hiblue] {pt(-F_top)} -- {pt(F_top)};
\draw[gray] ({f(TH_V)}:0.36) arc[start angle={f(TH_V)}, end angle={f(TH_D)}, radius=0.36];
\node at ({f(0.5 * (TH_V + TH_D))}:0.5) {{$\psi$}};
\node[anchor=east] at {pt(0.8 * E_top + 0.08 * nd)} {{$\sqrt{{\gamma}}$}};
\node[anchor=north west, hiblue] at {pt(F_top + np.array([0.02, -0.06]))} {{$\sqrt{{\gamma}}\cos\psi$}};
\node[anchor=north west, gray] at {pt(polar(-50, UNIT + 0.04))} {{noise, sd $1$}};
\node at (0,-2.0) {{$\gamma\;\longrightarrow\;\gamma\cos^{{2}}\psi$}};
\end{{scope}}
% (c) conditional density of R when the policy replaces
\begin{{scope}}[shift={{(8.8,0)}}]
\node[ttl] at (2.1,{f(TOP)}) {{(c) safety margin}};
{tail_fill(ind, 'hired!35')}
{tail_fill(rec, 'black!30')}
\draw[thick] plot coordinates {{{coords(zip(rec['xs'], rec['ys']))}}};
\draw[thick, hired] plot coordinates {{{coords(zip(ind['xs'], ind['ys']))}}};
\draw[->] (0,{f(BASE)}) -- (4.1,{f(BASE)}) node[below left=1pt and -2pt] {{$R$}};
\draw[densely dashed] ({f(T_LEAD)},{f(BASE)}) -- ({f(T_LEAD)},{f(rec['peak'] + 0.3)}) node[above] {{$t_{{\mathrm{{lead}}}}$}};
\node[anchor=east] at ({f(T_LEAD - 0.2)},{f(BASE + 0.42)}) {{$\alpha$}};
\node[anchor=west] at {pt(LAB_REC)} {{$R\mid\tilde y$}};
\node[anchor=west, hired] at {pt(LAB_IND)} {{$R\mid z$}};
\draw[|<->|, semithick] ({f(T_LEAD)},{f(BASE - 0.3)}) -- ({f(rec['m'])},{f(BASE - 0.3)})
  node[right] {{$\zeta_\alpha s_R$}};
\draw[|<->|, semithick, hired] ({f(T_LEAD)},{f(BASE - 0.72)}) -- ({f(ind['m'])},{f(BASE - 0.72)})
  node[right] {{$\zeta_\alpha e^{{\lloss}}s_R$}};
\end{{scope}}
\end{{tikzpicture}}
\caption{{Mechanism of the information loss. (a)~In a time-shift population the units follow one degradation path and differ only in their position along it, so neighbouring units differ along the tangent $\dot x$, which by \eqref{{eq:sens}} is the sensitivity to the remaining life. (b)~In the whitened record, drawn for $d=2$, the spread of the remaining life moves the record along $\dhat$ with standard deviation $\sqrt{{\gamma}}$, and the noise has unit standard deviation in every direction. Projecting onto $\mathbf v$ keeps $\sqrt{{\gamma}}\cos\psi$ of the signal and all of the noise, so the signal-to-noise ratio falls from $\gamma$ to $\gamma\cos^{{2}}\psi$, which gives \eqref{{eq:exact}}. (c)~Conditional densities of $R$ when a predictive replacement policy replaces: each has probability $\alpha$ below $t_{{\mathrm{{lead}}}}$, so its centre lies $\zeta_\alpha$ standard deviations above it. The indicator widens the density by $e^{{\lloss}}$ \eqref{{eq:mmse}} and the safety margin with it; $e^{{\lloss}}$ is drawn as ${f(INFL)}$ for legibility.}}
\label{{fig:lossmech}}
\end{{figure*}}
%</mechfig:loss>"""

# =========================================================== Figure 3 =====
# ---- (a) the signal vector for d = 2 -------------------------------------
SC = 0.95
d0 = np.array([1.6, 1.2])
d_eq = d0 * 1.5                            # equal logarithmic rates
d_un = d0 * np.array([1.8, 1.15])          # g1 > g2
assert abs(np.log(d_eq / d0)[0] - np.log(d_eq / d0)[1]) < 1e-12
assert np.log(d_un / d0)[0] > np.log(d_un / d0)[1]
ang0 = math.degrees(math.atan2(d0[1], d0[0]))
ang_eq = math.degrees(math.atan2(d_eq[1], d_eq[0]))
ang_un = math.degrees(math.atan2(d_un[1], d_un[0]))
assert abs(ang_eq - ang0) < 1e-9 and ang_un < ang0
D0, DEQ, DUN = SC * d0, SC * d_eq, SC * d_un

# ---- (b) a sector of the sphere seen from v -----------------------------
# Orthographic projection centred on v: the set of constant psi is the circle
# of radius sin(psi), and great circles through v are the radial lines. The
# sector shows three level sets; d-hat sits on the outermost, straight right
# of v, so the radial direction is horizontal and the level set vertical.
RB = 2.45                                    # radius of the outer level set
LEV = (0.7, 1.4, RB)
SECT = 40.0                                  # half-angle of the sector
VB = np.array([-1.55, 0.0])                  # v, relative to the panel
Pb = VB + np.array([RB, 0.0])
G = Pb + np.array([-0.6, 0.0])               # along the great circle, to v
Tt = Pb + np.array([0.0, 0.62])              # along the level set
TOT = Pb + np.array([-0.6, 0.62])
C_SHIFT = np.array([6.35, 1.75])

# ---- (c) a path of d-hat of length Phi, its midpoint, the cap ------------
m0 = np.ones(3) / math.sqrt(3.0)
e1 = np.array([1.0, -1.0, 0.0]) / math.sqrt(2.0)
e2 = np.cross(m0, e1)


def sphere_path(t):
    a = 0.52 * (2 * t - 1)
    b = 0.30 * (1 - (2 * t - 1) ** 2) - 0.13
    p = m0 + a * e1 + b * e2
    return p / np.linalg.norm(p)


T = np.linspace(0.0, 1.0, 4001)
Pp = np.array([sphere_path(t) for t in T])
seg = np.arccos(np.clip((Pp[1:] * Pp[:-1]).sum(1), -1, 1))
cum = np.concatenate([[0.0], np.cumsum(seg)])
PHI = cum[-1]
k_mid = int(np.searchsorted(cum, PHI / 2))
M = Pp[k_mid] / np.linalg.norm(Pp[k_mid])
dist = np.arccos(np.clip(Pp @ M, -1, 1))
assert dist.max() <= PHI / 2 + 1e-4, (np.degrees(dist.max()), np.degrees(PHI / 2))
# the view: from m0, with e3 up
n = m0
ey = np.array([0.0, 0.0, 1.0]) - n[2] * n
ey /= np.linalg.norm(ey)
ex = np.cross(ey, n)
RC = 1.8
S_SHIFT = np.array([11.15, 1.75])


def proj3(p):
    assert p @ n > 0.05, "drawn point on the hidden hemisphere"
    return RC * np.array([p @ ex, p @ ey])


def slerp(a, b, k=40):
    om = math.acos(np.clip(a @ b, -1, 1))
    return [(math.sin((1 - s) * om) * a + math.sin(s * om) * b) / math.sin(om)
            for s in np.linspace(0, 1, k)]


f1 = np.cross(M, ey)
f1 /= np.linalg.norm(f1)
f2 = np.cross(M, f1)
cap = [math.cos(PHI / 2) * M + math.sin(PHI / 2) * (math.cos(p) * f1 + math.sin(p) * f2)
       for p in np.linspace(0, 2 * math.pi, 121)]
path_c = [Pp[i] for i in range(0, len(T), 100)] + [Pp[-1]]
chord = slerp(M, Pp[-1])                     # v to the end of the path
q1 = proj3(Pp[int(np.searchsorted(cum, 0.25 * PHI))])
q3 = proj3(Pp[int(np.searchsorted(cum, 0.75 * PHI))])
PM = proj3(M)
cap2 = np.array([proj3(p) for p in cap])
CH_MID = proj3(chord[int(0.4 * len(chord))])

fig_arc = rf"""%<mechfig:arc> generated by make_mechfigs.py -- edit there, not here
\begin{{figure*}}[tb]
\centering
\begin{{tikzpicture}}[font=\scriptsize, >={{Latex[length=1.5mm]}},
  ttl/.style={{font=\footnotesize, anchor=north}}]
% (a) rotation from unequal logarithmic rates, d = 2
\node[ttl] at (1.85,{f(TOP)}) {{(a) unequal rates}};
\draw[->] (0,0) -- (3.55,0) node[below left=1pt and -2pt] {{$\dvec_1$}};
\draw[->] (0,0) -- (0,2.75) node[below left=-2pt and 1pt] {{$\dvec_2$}};
\node[anchor=north west] at (0.12,3.1) {{$\|\dot{{\dhat}}\|=\sqrt{{p_1p_2}}\,|\dot g_1-\dot g_2|$}};
\draw[dotted, gray] (0,0) -- {pt(1.95 * D0)};
\draw[hired] (0,0) -- {pt(DUN)};
\draw[->, very thick] (0,0) -- {pt(D0)} node[above left=0pt and -1pt] {{$\dvec(t)$}};
\draw[->, thick, gray] {pt(D0)} -- {pt(DEQ)} node[above left=-1pt and 0pt] {{$\dot g_1=\dot g_2$}};
\draw[->, thick, hired] {pt(D0)} -- {pt(DUN)} node[right] {{$\dot g_1>\dot g_2$}};
\draw[hired] ({f(ang_un)}:1.05) arc[start angle={f(ang_un)}, end angle={f(ang0)}, radius=1.05];
\node[hired, anchor=north west] at {pt(polar(ang_un, 1.05) + np.array([0.05, -0.06]))} {{turn}};
% (b) a sector of the sphere seen from v
\begin{{scope}}[shift={{{pt(C_SHIFT)}}}]
\node[ttl] at (0,{f(TOP - C_SHIFT[1])}) {{(b) the sphere seen from $\mathbf v$}};
""" + "".join(rf"""\draw[gray!70, densely dotted] {pt(VB + polar(-SECT, r))} arc[start angle={f(-SECT)}, end angle={f(SECT)}, radius={f(r)}];
""" for r in LEV) + rf"""\node[gray, anchor=north] at {pt(VB + polar(-SECT, RB) + np.array([0.0, -0.04]))} {{$\psi=\mathrm{{const}}$}};
\draw[dashed, gray] {pt(VB)} -- {pt(G)};
\node[gray, anchor=south] at {pt(VB + np.array([1.2, 0.04]))} {{$\psi$}};
\fill[hiblue] {pt(VB)} circle (1.6pt);
\node[hiblue, anchor=north] at {pt(VB + np.array([0.0, -0.06]))} {{$\mathbf v$}};
\draw[->, thick, higreen] {pt(Pb)} -- {pt(G)};
\node[anchor=north east, higreen] at {pt(G + np.array([0.55, -0.08]))} {{$\delta\psi\neq0$}};
\draw[->, thick, gray] {pt(Pb)} -- {pt(Tt)};
\node[anchor=west, gray] at {pt(Tt + np.array([0.06, 0.0]))} {{$\delta\psi=0$}};
\draw[->, very thick] {pt(Pb)} -- {pt(TOT)};
\node[anchor=south east] at {pt(TOT + np.array([-0.02, 0.02]))} {{$\dot{{\dhat}}$}};
\fill {pt(Pb)} circle (1.5pt);
\node[anchor=north west] at {pt(Pb + np.array([0.06, -0.05]))} {{$\dhat$}};
\end{{scope}}
% (c) the arc bound
\begin{{scope}}[shift={{{pt(S_SHIFT)}}}]
\node[ttl] at (0,{f(TOP - S_SHIFT[1])}) {{(c) the arc bound}};
\draw[gray!60] (0,0) circle ({f(RC)});
\fill[hiblue!10] plot[smooth cycle] coordinates {{{coords(cap2[:-1])}}};
\draw[hiblue, densely dashed] plot[smooth cycle] coordinates {{{coords(cap2[:-1])}}};
\draw[->, very thick] plot[smooth] coordinates {{{coords(proj3(p) for p in path_c)}}};
\draw[hiblue, semithick] plot[smooth] coordinates {{{coords(proj3(p) for p in chord)}}};
\node[hiblue, anchor=south] at {pt(CH_MID + np.array([0.0, 0.04]))} {{$\psi$}};
\fill[hiblue] {pt(PM)} circle (1.6pt);
\node[hiblue, anchor=north] at {pt(PM + np.array([0.0, -0.05]))} {{$\mathbf v$}};
\node[anchor=north] at {pt(q1 + np.array([0.0, -0.2]))} {{$\Phi/2$}};
\node[anchor=north] at {pt(q3 + np.array([0.0, -0.2]))} {{$\Phi/2$}};
\node[hiblue, anchor=north] at {pt(np.array([PM[0], cap2[:, 1].min() - 0.05]))} {{$\psi\le\Phi/2$}};
\end{{scope}}
\end{{tikzpicture}}
\caption{{Mechanism of the rotation and of the arc bound. (a)~The signal vector $\dvec$ of \eqref{{eq:dvec}} for $d=2$: when both components grow at the same logarithmic rate the direction $\dhat$ is unchanged, and it turns only when the rates differ, at the speed \eqref{{eq:repl}}. (b)~A sector of the unit sphere seen from $\mathbf v$: the sets of constant $\psi$, and hence of constant loss, are circles around $\mathbf v$, and the great circles through $\mathbf v$ are radial lines. Only the component of $\dot{{\dhat}}$ along the great circle through $\mathbf v$ changes $\psi$ ($\delta\psi\neq0$); the other $d-2$ components move $\dhat$ within its level set ($\delta\psi=0$). (c)~A path of $\dhat$ of length $\Phi$, split at its midpoint into two halves of length $\Phi/2$. Every point of the path lies within $\Phi/2$ of the midpoint along the path, and therefore on the sphere, so an indicator $\mathbf v$ at the midpoint keeps $\psi\le\Phi/2$ (shaded cap), which gives \eqref{{eq:arcbound}}. Panels (b) and (c) hold in any dimension and are drawn for $d=3$.}}
\label{{fig:arcmech}}
\end{{figure*}}
%</mechfig:arc>"""


def put(t, tag, block):
    pat = re.compile(r"%<mechfig:" + tag + r">.*?%</mechfig:" + tag + r">", re.S)
    if len(pat.findall(t)) != 1:
        raise SystemExit(f"theory.tex: expected one {tag} block")
    return pat.sub(lambda _: block, t)


if __name__ == "__main__":
    t = io.open(TEX, encoding="utf-8").read()
    t = put(t, "loss", fig_loss)
    t = put(t, "arc", fig_arc)
    io.open(TEX, "w", encoding="utf-8", newline="").write(t)
    print(f"Phi = {math.degrees(PHI):.1f} deg; max angle to midpoint "
          f"{math.degrees(dist.max()):.1f} deg <= {math.degrees(PHI / 2):.1f}")
    print(f"turn in (a): {ang0 - ang_un:.1f} deg; zeta = {ZETA:.3f}")
    print("mechfigs written into theory.tex")
